name: Create Release Build

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.11.0
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.41.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate a release build
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter_app_release_build
          path: build/app/outputs/flutter-apk/app-release.apk

